name: Build Dev Container

inputs:
  dev-container-name:
    description: 'Dev container name to build and release'
    required: true
  dotnet-sdk-version:
    description: '.NET SDK version'
    required: true
  github-token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: "composite"

  steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Login to Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Create helper variable with .NET SDK version for Docker image tagging
      shell: bash
      run: |
        if [[ "${{ inputs.dev-container-name }}" == dotnet* ]]; then
          echo "ADDITIONAL_TAG=sdk-${{ inputs.dotnet-sdk-version }}" >> $GITHUB_ENV
        else
          echo "ADDITIONAL_TAG=" >> $GITHUB_ENV
        fi

    - name: Set image tag
      shell: bash
      run: |
        if [ -n "${{ env.ADDITIONAL_TAG }}" ]; then
          echo "IMAGE_TAG=v${{ github.run_number }}, latest, ${{ env.ADDITIONAL_TAG }}" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=v${{ github.run_number }}, latest" >> $GITHUB_ENV
        fi

    - name: Log certain derived environment variables
      shell: bash
      run: |
        echo "ADDITIONAL_TAG=${{ env.ADDITIONAL_TAG }}"
        echo "dotnet-sdk-version=${{ inputs.dotnet-sdk-version }}"          
        echo "IMAGE_TAG=${{ env.IMAGE_TAG }}"

    - name: Pre-build dev container image '${{ inputs.dev-container-name }}'
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/mu88/devcontainers-${{ inputs.dev-container-name }}
        cacheFrom: ghcr.io/mu88/devcontainers-${{ inputs.dev-container-name }}
        push: filter
        refFilterForPush: refs/heads/${{ github.event.repository.default_branch }}
        imageTag: ${{ env.IMAGE_TAG }}
        subFolder: devcontainers/${{ inputs.dev-container-name }}
        configFile: devcontainers/${{ inputs.dev-container-name }}/devcontainer.json
