name: Combined CI / Release

on:
  workflow_dispatch:
    inputs:
      dotnet_sdk_version:
        description: '.NET SDK version'
        required: true
  push:
    tags:
      - '*'
    branches:
      - '**'

env:
  DEFAULT_DOTNET_SDK_VERSION: 9.0.306

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        package: [
          dotnet,
          dotnet-playwright,
          jekyll,
          node-devcontainer-cli
        ]

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set .NET SDK version environment variable
        run: |
          if [ -z "${{ github.event.inputs.dotnet_sdk_version }}" ]; then
            echo "DOTNET_SDK_VERSION=${{ env.DEFAULT_DOTNET_SDK_VERSION }}" >> $GITHUB_ENV
          else
            echo "DOTNET_SDK_VERSION=${{ github.event.inputs.dotnet_sdk_version }}" >> $GITHUB_ENV
          fi

      - name: Create helper variable with .NET SDK version for Docker image tagging
        run: |
          if [[ "${{ matrix.package }}" == dotnet* ]]; then
            echo "ADDITIONAL_TAG=sdk-${{ env.DOTNET_SDK_VERSION }}" >> $GITHUB_ENV
          else
            echo "ADDITIONAL_TAG=" >> $GITHUB_ENV
          fi

      - name: Set image tag
        run: |
          if [ -n "${{ env.ADDITIONAL_TAG }}" ]; then
            echo "IMAGE_TAG=v${{ github.run_number }}, latest, ${{ env.ADDITIONAL_TAG }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=v${{ github.run_number }}, latest" >> $GITHUB_ENV
          fi

      - name: Determine push behavior (only push new dev container on default branch)
        run: |
          if [[ "${{ github.ref_name }}" == "${{ github.event.repository.default_branch }}" ]]; then
            echo "PUSH=always" >> $GITHUB_ENV
          else
            echo "PUSH=never" >> $GITHUB_ENV
          fi

      - name: Log certain derived environment variables
        run: |
          echo "ADDITIONAL_TAG=${{ env.ADDITIONAL_TAG }}"
          echo "DOTNET_SDK_VERSION=${{ env.DOTNET_SDK_VERSION }}"          
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}"
          echo "PUSH=${{ env.PUSH }}"

      - name: Pre-build dev container image '${{ matrix.package }}'
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/mu88/devcontainers-${{ matrix.package }}
          cacheFrom: ghcr.io/mu88/devcontainers-${{ matrix.package }}
          push: ${{ env.PUSH }}
          imageTag: ${{ env.IMAGE_TAG }}
          subFolder: devcontainers/${{ matrix.package }}
          configFile: devcontainers/${{ matrix.package }}/devcontainer.json
