name: Combined CI / Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - '**'

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        package: [
          dotnet
        ]

    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pre-build dev container image '${{ matrix.package }}'
        uses: devcontainers/ci@v0.3
        with:
          imageName: registry.hub.docker.com/mu88/devcontainers-${{ matrix.package }}
          cacheFrom: registry.hub.docker.com/mu88/devcontainers-${{ matrix.package }}
          push: always
          imageTag: 'v${{ github.run_number }}, latest'
          subFolder: '${{ matrix.package }}'
          configFile: './${{ matrix.package }}/devcontainer.json'
